var OA_output = new Array(); 
OA_output['3'] = '';
OA_output['3'] += "<"+"div id=\'ox_d421d9ac46907eda7c35363d91b2a97f\' style=\'display: inline;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/images/1x1.gif\' alt=\'\' title=\'\' border=\'0\' /><"+"/div>\n";
OA_output['3'] += "<"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['3'] += "var ox_swf = new FlashObject(\'http://ads.vinmedia.com.vn/openx/www/images/2de1f274b8aecd7a16336fee2a0f1948.swf\', \'Advertisement\', \'310\', \'242\', \'11\');\n";
OA_output['3'] += "ox_swf.addVariable(\'alink1\', \'http%3A%2F%2Fads.vinmedia.com.vn%2Fopenx%2Fwww%2Fdelivery%2Fck.php%3Foaparams%3D2__bannerid%3D1__zoneid%3D3__cb%3D29c8a542a1__oadest%3Dhttp%253A%252F%252Fwww.duocminhphat.com%252Fcansua3_cansua3%252B.html\');\n";
OA_output['3'] += "ox_swf.addVariable(\'atar1\', \'_blank\');\n";
OA_output['3'] += "ox_swf.addParam(\'allowScriptAccess\',\'always\');\n";
OA_output['3'] += "ox_swf.write(\'ox_d421d9ac46907eda7c35363d91b2a97f\');\n";
OA_output['3'] += "if (ox_swf.installedVer.versionIsValid(ox_swf.getAttribute(\'version\'))) { document.write(\"<"+"div id=\'beacon_29c8a542a1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=3&amp;loc=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;referer=https%3A%2F%2Fwww.google.com.vn%2F&amp;cb=29c8a542a1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\"); }\n";
OA_output['3'] += "// ]]> --><"+"/script>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div id=\'ox_3d941b0a141c0270607eaa6ca6c58a6d\' style=\'display: inline;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/images/1x1.gif\' alt=\'\' title=\'\' border=\'0\' /><"+"/div>\n";
OA_output['4'] += "<"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['4'] += "var ox_swf = new FlashObject(\'http://img.webphunu.net/Upload/flash/quang-cao/top-banner/Webphunu-chu-top%20banner-650-100.swf\', \'Advertisement\', \'650\', \'100\', \'4\');\n";
OA_output['4'] += "ox_swf.addParam(\'allowScriptAccess\',\'always\');\n";
OA_output['4'] += "ox_swf.write(\'ox_3d941b0a141c0270607eaa6ca6c58a6d\');\n";
OA_output['4'] += "if (ox_swf.installedVer.versionIsValid(ox_swf.getAttribute(\'version\'))) { document.write(\"<"+"div id=\'beacon_a6054cf50e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=4&amp;campaignid=3&amp;zoneid=4&amp;OACCAP=1000&amp;loc=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;referer=https%3A%2F%2Fwww.google.com.vn%2F&amp;cb=a6054cf50e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\"); }\n";
OA_output['4'] += "// ]]> --><"+"/script>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'ox_89aa1b1a31d37f6228ee29a3b0cc05e3\' style=\'display: inline;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/images/1x1.gif\' alt=\'\' title=\'\' border=\'0\' /><"+"/div>\n";
OA_output['5'] += "<"+"script type=\'text/javascript\'><"+"!--// <"+"![CDATA[\n";
OA_output['5'] += "var ox_swf = new FlashObject(\'http://img.webphunu.net/Upload/flash/quang-cao/Right-banner/BANNER-KHAI%20GIANG-link.swf\', \'Advertisement\', \'310\', \'245\', \'4\');\n";
OA_output['5'] += "ox_swf.addVariable(\'clickTARGET\', \'_blank\');\n";
OA_output['5'] += "ox_swf.addVariable(\'clickTAG\', \'http%3A%2F%2Fads.vinmedia.com.vn%2Fopenx%2Fwww%2Fdelivery%2Fck.php%3Foaparams%3D2__bannerid%3D5__zoneid%3D5__cb%3Db1ee4bf9d1__oadest%3Dhttps%253A%252F%252Fwww.facebook.com%252FTrungTamLuyenThiEfaThanhXuan\');\n";
OA_output['5'] += "ox_swf.addParam(\'allowScriptAccess\',\'always\');\n";
OA_output['5'] += "ox_swf.write(\'ox_89aa1b1a31d37f6228ee29a3b0cc05e3\');\n";
OA_output['5'] += "if (ox_swf.installedVer.versionIsValid(ox_swf.getAttribute(\'version\'))) { document.write(\"<"+"div id=\'beacon_b1ee4bf9d1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=5&amp;campaignid=1&amp;zoneid=5&amp;loc=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;referer=https%3A%2F%2Fwww.google.com.vn%2F&amp;cb=b1ee4bf9d1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\"); }\n";
OA_output['5'] += "// ]]> --><"+"/script>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"script type=\"text/javascript\" src=\"http://webphunu.net/File/Js/jquery.1.7.2.js\"><"+"/script>\n";
OA_output['7'] += "<"+"script type=\"text/javascript\">\n";
OA_output['7'] += "$(document).ready(function () {\n";
OA_output['7'] += "var content = document.getElementById(\'float_content_right\');\n";
OA_output['7'] += "var float_right = document.getElementById(\'float_right\');\n";
OA_output['7'] += "var hide = document.getElementById(\'hide_float_right\');\n";
OA_output['7'] += "var addon_right = document.getElementById(\'addon_right\');\n";
OA_output['7'] += "$(window).scroll(function () {\n";
OA_output['7'] += "var i = $(window).scrollTop();\n";
OA_output['7'] += "if (i >= 300) {\n";
OA_output['7'] += "content.style.display = \"block\";\n";
OA_output['7'] += "hide.style.display = \"block\";\n";
OA_output['7'] += "addon_right.style.display = \"none\";\n";
OA_output['7'] += "float_right.style.width = \"0px\";\n";
OA_output['7'] += "hide_link.style.display = \"block\";\n";
OA_output['7'] += "}\n";
OA_output['7'] += "if (i <"+" 300) {\n";
OA_output['7'] += "content.style.display = \"none\";\n";
OA_output['7'] += "hide.style.display = \"none\";\n";
OA_output['7'] += "addon_right.style.display = \"block\";\n";
OA_output['7'] += "float_right.style.width = \"30px\";\n";
OA_output['7'] += "hide_link.style.display = \"none\";\n";
OA_output['7'] += "}\n";
OA_output['7'] += "});\n";
OA_output['7'] += "});\n";
OA_output['7'] += "function hide_float_right() {\n";
OA_output['7'] += "var content = document.getElementById(\'float_content_right\');\n";
OA_output['7'] += "var float_right = document.getElementById(\'float_right\');\n";
OA_output['7'] += "var hide = document.getElementById(\'hide_float_right\');\n";
OA_output['7'] += "var addon_right = document.getElementById(\'addon_right\');\n";
OA_output['7'] += "var hide_link = document.getElementById(\'hide_link\');\n";
OA_output['7'] += "if (content.style.display == \"block\") {\n";
OA_output['7'] += "content.style.display = \"none\";\n";
OA_output['7'] += "hide.style.display = \"none\";\n";
OA_output['7'] += "addon_right.style.display = \"block\";\n";
OA_output['7'] += "float_right.style.width = \"30px\";\n";
OA_output['7'] += "hide_link.style.display = \"none\";\n";
OA_output['7'] += "}\n";
OA_output['7'] += "else {\n";
OA_output['7'] += "content.style.display = \"block\";\n";
OA_output['7'] += "hide.style.display = \"block\";\n";
OA_output['7'] += "addon_right.style.display = \"none\";\n";
OA_output['7'] += "float_right.style.width = \"0px\";\n";
OA_output['7'] += "hide_link.style.display = \"block\";\n";
OA_output['7'] += "}\n";
OA_output['7'] += "}\n";
OA_output['7'] += "<"+"/script>\n";
OA_output['7'] += "<"+"style>\n";
OA_output['7'] += "* html #float_ck {position:absolute;top: expression(( 0 - float_ck.offsetHeight + ( document.documentElement.clientHeight ? document.documentElement.clientHeight : document.body.clientHeight ) + ( ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop ) -1) + \'px\' );}\n";
OA_output['7'] += "* html #float_right {position:absolute;bottom:0;}\n";
OA_output['7'] += "* html #addon_right {position:absolute;bottom:0;}\n";
OA_output['7'] += "#float_ck { position: fixed;right: 0px; bottom: 0px; z-index: 9999;width:300px;height:250px;margin:0;padding:0;}\n";
OA_output['7'] += "#float_content_right {border: 0px solid #01AEF0;display:none;}\n";
OA_output['7'] += "#float_right {position:fixed;right:0;bottom:0;width:30px;height:250px;z-index:9999;display:block;background:transparent;overflow:hidden;}\n";
OA_output['7'] += "#float_right a {background: transparent; padding: 2px 14px; color: #FFF;text-align:right; font-size: 11px;text-decoration:none;position: absolute;top: 23px;}\n";
OA_output['7'] += "#hide_float_right {text-align:right; font-size: 11px;display:none;position: absolute;right: 3px;top: 3px;}\n";
OA_output['7'] += "#hide_float_right a {background: transparent;color: #FFF;text-decoration:none;padding: 0px 10px 40px 10px;}\n";
OA_output['7'] += "#addon_right{position: fixed; overflow: hidden; bottom: 0px; right: 30px; z-index: 9999;}\n";
OA_output['7'] += "#hide_link {text-align:right; font-size: 11px;display:none;position: absolute;right: 3px;top: 25px;}\n";
OA_output['7'] += "#hide_link a {background: transparent;color: #FFF;text-decoration:none;display:block;width:295px;height:222px;}\n";
OA_output['7'] += "<"+"/style>\n";
OA_output['7'] += "<"+"div id=\"float_ck\">\n";
OA_output['7'] += "<"+"div id=\"addon_right\">\n";
OA_output['7'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/90x12-cansua3.swf\" width=\"90\" height=\"120\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\" allowScriptAccess=\"always\"/>\n";
OA_output['7'] += "<"+"/div>\n";
OA_output['7'] += "<"+"div id=\"float_right\">\n";
OA_output['7'] += "<"+"a href=\"javascript:hide_float_right()\">&nbsp;<"+"/a>\n";
OA_output['7'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/30x25-cansua3.swf\" width=\"30\" height=\"250\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\" allowScriptAccess=\"always\"/>\n";
OA_output['7'] += "<"+"/div>\n";
OA_output['7'] += "<"+"div id=\"hide_float_right\">\n";
OA_output['7'] += "<"+"a href=\"javascript:hide_float_right()\">&nbsp;<"+"/a>\n";
OA_output['7'] += "<"+"/div>\n";
OA_output['7'] += "<"+"div id=\"hide_link\">\n";
OA_output['7'] += "<"+"a href=\"http://ads.vinmedia.com.vn/openx/www/delivery/ck.php?oaparams=2__bannerid=7__zoneid=7__cb=4f5e4c3bf7__oadest=http%3A%2F%2Fwww.duocminhphat.com%2Fcansua3%2B.html\" target=\"_blank\"><"+"/a>\n";
OA_output['7'] += "<"+"/div>\n";
OA_output['7'] += "<"+"div id=\"float_content_right\">\n";
OA_output['7'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/300x2-cansua3.swf\" width=\"300\" height=\"250\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\"  allowScriptAccess=\"always\"/>\n";
OA_output['7'] += "<"+"/div>\n";
OA_output['7'] += "<"+"/div><"+"div id=\'beacon_4f5e4c3bf7\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=7&amp;campaignid=1&amp;zoneid=7&amp;loc=1&amp;referer=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;cb=4f5e4c3bf7\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['8'] = '';
OA_output['8'] += "<"+"script type=\"text/javascript\" src=\"http://webphunu.net/File/Js/jquery.1.7.2.js\"><"+"/script>\n";
OA_output['8'] += "<"+"script type=\"text/javascript\">\n";
OA_output['8'] += "$(document).ready(function () {\n";
OA_output['8'] += "var content = document.getElementById(\'float_content_right\');\n";
OA_output['8'] += "var float_right = document.getElementById(\'float_right\');\n";
OA_output['8'] += "var hide = document.getElementById(\'hide_float_right\');\n";
OA_output['8'] += "var addon_right = document.getElementById(\'addon_right\');\n";
OA_output['8'] += "$(window).scroll(function () {\n";
OA_output['8'] += "var i = $(window).scrollTop();\n";
OA_output['8'] += "if (i >= 700) {\n";
OA_output['8'] += "content.style.display = \"block\";\n";
OA_output['8'] += "hide.style.display = \"block\";\n";
OA_output['8'] += "addon_right.style.display = \"none\";\n";
OA_output['8'] += "float_right.style.width = \"0px\";\n";
OA_output['8'] += "hide_link.style.display = \"block\";\n";
OA_output['8'] += "}\n";
OA_output['8'] += "if (i <"+" 700) {\n";
OA_output['8'] += "content.style.display = \"none\";\n";
OA_output['8'] += "hide.style.display = \"none\";\n";
OA_output['8'] += "addon_right.style.display = \"block\";\n";
OA_output['8'] += "float_right.style.width = \"30px\";\n";
OA_output['8'] += "hide_link.style.display = \"none\";\n";
OA_output['8'] += "}\n";
OA_output['8'] += "});\n";
OA_output['8'] += "});\n";
OA_output['8'] += "function hide_float_right() {\n";
OA_output['8'] += "var content = document.getElementById(\'float_content_right\');\n";
OA_output['8'] += "var float_right = document.getElementById(\'float_right\');\n";
OA_output['8'] += "var hide = document.getElementById(\'hide_float_right\');\n";
OA_output['8'] += "var addon_right = document.getElementById(\'addon_right\');\n";
OA_output['8'] += "var hide_link = document.getElementById(\'hide_link\');\n";
OA_output['8'] += "if (content.style.display == \"block\") {\n";
OA_output['8'] += "content.style.display = \"none\";\n";
OA_output['8'] += "hide.style.display = \"none\";\n";
OA_output['8'] += "addon_right.style.display = \"block\";\n";
OA_output['8'] += "float_right.style.width = \"30px\";\n";
OA_output['8'] += "hide_link.style.display = \"none\";\n";
OA_output['8'] += "}\n";
OA_output['8'] += "else {\n";
OA_output['8'] += "content.style.display = \"block\";\n";
OA_output['8'] += "hide.style.display = \"block\";\n";
OA_output['8'] += "addon_right.style.display = \"none\";\n";
OA_output['8'] += "float_right.style.width = \"0px\";\n";
OA_output['8'] += "hide_link.style.display = \"block\";\n";
OA_output['8'] += "}\n";
OA_output['8'] += "}\n";
OA_output['8'] += "<"+"/script>\n";
OA_output['8'] += "<"+"style>\n";
OA_output['8'] += "* html #float_ck {position:absolute;top: expression(( 0 - float_ck.offsetHeight + ( document.documentElement.clientHeight ? document.documentElement.clientHeight : document.body.clientHeight ) + ( ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop ) -1) + \'px\' );}\n";
OA_output['8'] += "* html #float_right {position:absolute;bottom:0;}\n";
OA_output['8'] += "* html #addon_right {position:absolute;bottom:0;}\n";
OA_output['8'] += "#float_ck { position: fixed;right: 0px; bottom: 0px; z-index: 9999;width:300px;height:250px;margin:0;padding:0;}\n";
OA_output['8'] += "#float_content_right {border: 0px solid #01AEF0;display:none;}\n";
OA_output['8'] += "#float_right {position:fixed;right:0;bottom:0;width:30px;height:250px;z-index:9999;display:block;background:transparent;overflow:hidden;}\n";
OA_output['8'] += "#float_right a {background: transparent; padding: 2px 14px; color: #FFF;text-align:right; font-size: 11px;text-decoration:none;position: absolute;top: 23px;}\n";
OA_output['8'] += "#hide_float_right {text-align:right; font-size: 11px;display:none;position: absolute;right: 3px;top: 3px;}\n";
OA_output['8'] += "#hide_float_right a {background: transparent;color: #FFF;text-decoration:none;padding: 0px 10px 40px 10px;}\n";
OA_output['8'] += "#addon_right{position: fixed; overflow: hidden; bottom: 0px; right: 30px; z-index: 9999;}\n";
OA_output['8'] += "#hide_link {text-align:right; font-size: 11px;display:none;position: absolute;right: 3px;top: 25px;}\n";
OA_output['8'] += "#hide_link a {background: transparent;color: #FFF;text-decoration:none;display:block;width:295px;height:222px;}\n";
OA_output['8'] += "<"+"/style>\n";
OA_output['8'] += "<"+"div id=\"float_ck\">\n";
OA_output['8'] += "<"+"div id=\"addon_right\">\n";
OA_output['8'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/fecafovit/addon-fecafovit-100-120.swf\" width=\"90\" height=\"120\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\" wmode=\"transparent\" allowScriptAccess=\"always\"/>\n";
OA_output['8'] += "<"+"/div>\n";
OA_output['8'] += "<"+"div id=\"float_right\">\n";
OA_output['8'] += "<"+"a href=\"javascript:hide_float_right()\">&nbsp;<"+"/a>\n";
OA_output['8'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/fecafovit/banner-fecafovit-30-250.swf\" width=\"30\" height=\"250\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\" wmode=\"transparent\" allowScriptAccess=\"always\"/>\n";
OA_output['8'] += "<"+"/div>\n";
OA_output['8'] += "<"+"div id=\"hide_float_right\">\n";
OA_output['8'] += "<"+"a href=\"javascript:hide_float_right()\">&nbsp;<"+"/a>\n";
OA_output['8'] += "<"+"/div>\n";
OA_output['8'] += "<"+"div id=\"hide_link\">\n";
OA_output['8'] += "<"+"a href=\"http://ads.vinmedia.com.vn/openx/www/delivery/ck.php?oaparams=2__bannerid=8__zoneid=8__cb=946d65f518__oadest=http%3A%2F%2Fwww.duocminhphat.com%2Ffecafovit.html\" target=\"_blank\"><"+"/a>\n";
OA_output['8'] += "<"+"/div>\n";
OA_output['8'] += "<"+"div id=\"float_content_right\">\n";
OA_output['8'] += "<"+"embed src=\"http://ads.webphunu.net/tvcads/2013/fecafovit/banner-fecafovit300-250.swf\" width=\"300\" height=\"250\" quality=\"high\" pluginspage=\"http://www.macromedia.com/go/getflashplayer\" type=\"application/x-shockwave-flash\" menu=\"false\" wmode=\"transparent\" allowScriptAccess=\"always\"/>\n";
OA_output['8'] += "<"+"/div>\n";
OA_output['8'] += "<"+"/div><"+"div id=\'beacon_946d65f518\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=8&amp;campaignid=1&amp;zoneid=8&amp;loc=1&amp;referer=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;cb=946d65f518\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"a href=\'http://ads.vinmedia.com.vn/openx/www/delivery/ck.php?oaparams=2__bannerid=10__zoneid=10__cb=fb05207755__oadest=http%3A%2F%2Fhanoli.com.vn\' target=\'_blank\'><"+"img src=\'http://img.webphunu.net/Upload/sites/my-pham.jpg\' width=\'462\' height=\'343\' alt=\'Mỹ Phẩm Hanoli\' title=\'Mỹ Phẩm Hanoli\' border=\'0\' /><"+"/a><"+"div id=\'beacon_fb05207755\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.vinmedia.com.vn/openx/www/delivery/lg.php?bannerid=10&amp;campaignid=6&amp;zoneid=10&amp;loc=http%3A%2F%2Fwebphunu.net%2Ftin-tuc%2F4-mon-canh-ngon-nen-an-trong-mua-xuan-29768&amp;referer=https%3A%2F%2Fwww.google.com.vn%2F&amp;cb=fb05207755\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
